import type { Album, AlbumSlug, GalleryItem } from "./types";

/**
 * The /documentation gallery. Source: content.md §10.
 *
 * ── Ships live in v1 with zero photos. ────────────────────────────────────
 * This is not a feature flag and not a hidden route. Every album page renders
 * a real empty state ("nothing here yet") and stays correct when `ITEMS` is
 * empty, so photos can land later without redeploying any structure.
 *
 * Adding a photo means: run the ingest script, which strips EXIF including GPS,
 * resizes, converts, generates a blur placeholder and appends a stub object
 * here — then write the caption. One file, no component edits.
 *
 * Two standing rules once photos arrive: a yes from anyone identifiable before
 * it goes up, and EXIF and GPS stripped on the way in.
 */

export const ALBUMS: Album[] = [
  {
    slug: "jalan-jalan",
    code: "O1.1",
    name: "Jalan-jalan",
    blurb: "Travel and trips.",
  },
  {
    slug: "kerja",
    code: "O1.2",
    name: "Kerja",
    blurb: "IBM, the office, conferences, demos.",
  },
  {
    slug: "ngajar",
    code: "O1.3",
    name: "Ngajar",
    blurb: "Teaching: labs, review sessions, the whiteboard.",
  },
  {
    slug: "lomba",
    code: "O1.4",
    name: "Lomba",
    blurb: "GEMASTIK, Datathon, competition rooms.",
  },
  {
    slug: "organisasi",
    code: "O1.5",
    name: "Organisasi",
    blurb: "AIESEC, BETIS, BEM, RISTEK, Open House.",
  },
  {
    slug: "random",
    code: "O1.6",
    name: "Random",
    blurb: "The ones that don't fit.",
  },
];

/**
 * Empty on purpose. Every consumer must handle this being `[]` — that is the
 * v1 acceptance criterion, not a temporary state to code around.
 */
export const ITEMS: GalleryItem[] = [];

/**
 * A preview grid for an album that has no real photos yet. NOT part of
 * `ITEMS` and never counted by `albumCount` — the "ships with zero real
 * photos" fact stays true, and the required "nothing here yet" message still
 * renders unconditionally. This is what shows underneath it, so the page has
 * the visual weight of a real gallery rather than one line of grey text
 * repeated across six albums.
 *
 * The moment a real GalleryItem lands in `ITEMS` for an album, that album's
 * page stops rendering this — see `albumDisplayItems`.
 *
 * Generated by `pnpm placeholders:gallery`. Six shapes, varied aspect ratios
 * on purpose so the masonry grid reads as a photo grid rather than identical
 * cards, cycled across however many preview tiles an album shows.
 */
export const PLACEHOLDER_SHAPES = [
  { id: "a", width: 1200, height: 1500 },
  { id: "b", width: 1600, height: 1000 },
  { id: "c", width: 1400, height: 1400 },
  { id: "d", width: 1600, height: 900 },
  { id: "e", width: 1100, height: 1400 },
  { id: "f", width: 1500, height: 1050 },
] as const;

/** Same 8x5 blurred graphite tile the project placeholders use. */
const PLACEHOLDER_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAFCAIAAAD38zoCAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEUlEQVQImWNQM7THihjoIAEAtbgXcbAPCwcAAAAASUVORK5CYII=";

export function placeholderPreview(album: AlbumSlug, count = 4): GalleryItem[] {
  return PLACEHOLDER_SHAPES.slice(0, count).map((shape) => ({
    src: `/images/documentation/placeholder-${shape.id}.png`,
    alt: "Placeholder. A real photo from this album will replace this tile.",
    caption: undefined,
    kind: "photo" as const,
    album,
    width: shape.width,
    height: shape.height,
    blurDataURL: PLACEHOLDER_BLUR,
  }));
}

/**
 * What an album page actually renders: real items if there are any, the
 * preview grid otherwise. Never both — a real photo replaces the placeholder
 * that would have stood in for it, it does not sit alongside one.
 */
export function albumDisplayItems(slug: AlbumSlug): {
  items: GalleryItem[];
  isPlaceholder: boolean;
} {
  const real = itemsInAlbum(slug);
  return real.length > 0
    ? { items: real, isPlaceholder: false }
    : { items: placeholderPreview(slug), isPlaceholder: true };
}

export const GALLERY_COPY = {
  heading: "Documentation",
  blurb: "Photos and documentation, in the Indonesian student-org sense.",
  /** Shown on an album with no items yet. */
  emptyAlbum: "Nothing here yet.",
  emptyAlbumDetail: "Photos haven't been added yet.",
  /** Sits above the placeholder preview grid, so it reads as a mockup, not real photos. */
  previewLabel: "Preview: every tile below is a placeholder",
  previewDetail: "These are placeholder images, not real photos.",
  emptyIndex: "No photos up yet.",
  lightboxClose: "Close",
  lightboxPrev: "Previous photo",
  lightboxNext: "Next photo",
  /** Photo counts on the album index. */
  countNone: "empty",
  countOne: "1 photo",
  countMany: (n: number) => `${n} photos`,
  allAlbums: "All albums",
} as const;

export function albumBySlug(slug: string): Album | undefined {
  return ALBUMS.find((album) => album.slug === slug);
}

export function itemsInAlbum(slug: AlbumSlug): GalleryItem[] {
  return ITEMS.filter((item) => item.album === slug);
}

export function albumCount(slug: AlbumSlug): number {
  return itemsInAlbum(slug).length;
}
