/** Generated by scripts/make-placeholders.mjs. Do not edit by hand. */
export const PLACEHOLDER_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAFCAIAAAD38zoCAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEUlEQVQImWNQM7THihjoIAEAtbgXcbAPCwcAAAAASUVORK5CYII=";
